services:
  postgres:
    image: postgres:16
    container_name: medium-backend-tech-test-db
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logistics"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
